### MangoHud configuration file

### Legacy layout
legacy_layout=0

### pre defined presets
preset=1,2,3

### Set CPU information style
cpu_text=CPU
cpu_load_value=60,90
cpu_load_color=39F900,FDFD09,B22222

### Set GPU information style
gpu_text=GPU
gpu_load_value=60,90
gpu_load_color=39F900,FDFD09,B22222

## removes the time label
time_no_label

### Change the hud font size
font_size=24

### Outline text
text_outline

### Change the hud position
position=top-left

### Change the corner roundness
round_corners=10

### Hud dimensions
table_columns=5

### Color customization
text_color=FFFFFF

### Specify GPU with PCI bus ID
pci_dev=0000:01:00.0
