# Imperivm: Le Guerre Puniche

# Enable Gamescope
enable_gamescope

# Disable auto VRR
disable_auto_vrr

# Set framerate limit
set_framerate_limit 60

# Missing sound fixes
execute_prefix_winetricks sound \
  dmime dmsynth dmusic dswave dsound
