# Warsmash: Mod Engine

# Disable MangoHud
export MANGOHUD=0

# Use MangoHud's dlsym wrapper for OpenGL
command="mangohud --dlsym ${command}"

# Add brew to PATH (for Java)
export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"
